version: 0.1

phases:
  install:
    commands:
      - |
        npm install
  build:
    commands:
      - |
        npm run deploy:cicd
  post_build:
    commands:
      - |
        npm run test:remote
